import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";
import {
    ResizableHandle,
    ResizablePanel,
    ResizablePanelGroup,
} from "@/components/ui/resizable"
import {Sidebar} from "@/components/layout/Sidebar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className={'h-screen flex flex-col justify-center items-center'}>
            <Navbar />
            <ResizablePanelGroup direction="horizontal" className={'h-full w-full'}>
                <ResizablePanel defaultSize={20}>
                    <Sidebar />
                </ResizablePanel>
                <ResizableHandle />
                <ResizablePanel defaultSize={100}>
                    <div className="h-full w-full flex justify-center items-center">
                        {children}
                    </div>
                </ResizablePanel>
            </ResizablePanelGroup>
        </div>
        </body>
        </html>
    );
}
